### ISSUE TITLE
问卷系统中ng2-bootstrap模块加载问题

### ISSUE THREAD

**Issue by Chaiyelu** [angular-programming/issues#1]
![image](https://cloud.githubusercontent.com/assets/13944889/22134111/a82f06ba-deff-11e6-8987-50a0b9b2a7fa.png)

请问这个是什么问题，该如何解决。
另外代码中ng2-bootstrap文件目录，和现在用npm，install下来的目录不一样。
![image](https://cloud.githubusercontent.com/assets/13944889/22134123/b8126ae0-deff-11e6-9e3f-b32d0b2e27ef.png)
并没有ng2-bootstrap/component/这一级目录。#

**Comment by lightningtgc** [comment]
参见 https://github.com/angular-programming/angular2-questionnaire/issues/1
