### ISSUE TITLE
第444页的label写错

### ISSUE THREAD

**Issue by de8ug** [angular-programming/issues#10]
一共四个label，成对的第一个都写错成lable了

**Comment by ghost** [comment]
恩，确实是的，在17.1的HTML代码。
谢谢反馈~

**Comment by de8ug** [comment]
回复好快啊，顺便多说一个，449页中间`field-component.ts`这个文件名错了，中间是`.`不是`-`

**Comment by ghost** [comment]
哈哈，好的 ~
