### ISSUE TITLE
Angular单元测试一块

### ISSUE THREAD

**Issue by clfeng** [angular-programming/issues#11]
我是angular的初学者，学到angular单元测试一块的时候，对于344-349页的文件组织，以及要下载的包之类的摸不着头脑，希望能够有源码提供。另外感觉可以在将karma.config.js的配置之前大概讲解一下，要先安装哪些东西，还是基于前面的某一个文件的环境开始，以方便初学者学习，谢谢。

**Comment by ghost** [comment]
1. 关于测试依赖的一些包在 12.2 小节里有提到的，344页后面的内容是根据前面的一些准备工作以及通讯录例子继续讲解的。需要安装的一些依赖包在前面讲解的操作步骤都交代过的 ~
2. 另外karma.config.js是12.2小节里讲到的，是karma初始化命令自动生成的。karma.config.js 里面的配置确实没有展开讲解，谢谢反馈，我们会斟酌优化哈。
3. 当前github上的通讯录例子（https://github.com/angular-programming/angular2-contacts-demo ）暂时没有包含测试相关的代码，抱歉了。

**Comment by clfeng** [comment]
前面的配置，以及344开始前得配置我也都阅读了，刚刚也是试着用hello-world讲解一块那里的配置搭建好基础的开发环境，然后按照最初的karma，jasmine的配置去弄，只是这些配置都加在一起，还有加进detail组建一块的目录，过程中挺多要改的，所以常会遇到各种问题，所以希望能有一份代码可以对照着，让读者自己对比 看下问题出在哪里

**Comment by ghost** [comment]
恩，明白。
我们会在通讯录源码上陆续加一些测试例子。
