### ISSUE TITLE
模板表单的章节

### ISSUE THREAD

**Issue by liudianliang** [angular-programming/issues#13]
模板表单的章节的多次出现curContact，问下这个数据在哪里？到处找没找到，不是杜撰出来的吧？

**Comment by ghost** [comment]
`curContact` 表示当前的contact（current contact），为方便叙述而虚构出来的一个变量，就是一个普通的contact对象

**Comment by liudianliang** [comment]
每个章节的代码能分享出来吗？

**Comment by ghost** [comment]
贯穿整书的这个通讯录示例（https://github.com/angular-programming/angular2-contacts-demo ）放在github上。但每章节的一些零碎代码暂时没有整理出来。
