### ISSUE TITLE
http请求问题

### ISSUE THREAD

**Issue by sunnut** [angular-programming/issues#14]
当用http发送请求后(map&catch方式)，如果rest接口只返回状态码，结果返回null，http请求走的是catch流程，这个解决哈

**Comment by ghost** [comment]
确定 http 的 statusCode 是 200 么？

**Comment by sunnut** [comment]
确定呢

**Comment by sunnut** [comment]
http提示是对的 就是response是空

**Comment by sunnut** [comment]
有解决方法么

**Comment by ghost** [comment]
抱歉，上班时间比较忙，晚上再看看 ~

**Comment by sunnut** [comment]
恩恩 我也没辙 有空帮忙研究下 谢了哈

**Comment by sunnut** [comment]
通过一个方法解决了
filter(response => {
   if (!response['_body']) {
          response['_body'] = '{}';
   }
   return true;
})

**Comment by ghost** [comment]
我模拟了一下空的返回，但 http status code 为 200，没有进入catch分支的，你可以贴一下代码么？

**Comment by sunnut** [comment]
put(uri:any, data:any) {
    return this.getHttpByOpt('put', uri, data);
  }

getHttpByOpt(opt:any, uri:any, data:any) {
    let that = this;

    if (opt === 'post' || opt === 'put') {
      return that.http[opt](uri, JSON.stringify(data), {headers: this.headers}).filter(response => {
        if (!response['_body']) {
          response['_body'] = '{}';
        }
        return true;
      }).catch((res: Response) => {
        if (res.status === 401 && res.json().error === 'access token is expired') {
          return that.refreshTokenAndHttpDataAgain(opt, uri, data);
        } else if (res.status === 403
          && (res.json().error === 'access token not exist' || res.json().error === 'token not exist')) {
          that.backToLogin();
        } else if (res.status === 403
          && (res.json().error === 'access token is invalid' || res.json().error === 'token is invalid')) {
          that.backToLogin();
        } else {
          //return Observable.throw(res);
        }
      }).finally(() => {
        this.recoverHeader();
      });
    }

**Comment by sunnut** [comment]
//===================================================
  // 修改密码
  //===================================================
  modifyPassword(id: string, data: any) {
    return this.http.put(appConfig.iksServiceUrl + 'users/' + id + '/password', data)
      .map(this.extractData).catch(this.handleError);
  }

  extractData(res:any) {
      let body = res.json();
      return body || {};
  }

  handleError(error:any) {
      let errMsg = (error.message) ? error.message : error.status ? `${error.status} - ${error.statusText}` : 'Server error';
      return Observable.throw(errMsg);
  }

**Comment by ghost** [comment]
我用你的例子大概试了下还是正常的，错误信息帖一下？
