### ISSUE TITLE
Typescript解构出错

### ISSUE THREAD

**Issue by hileix** [angular-programming/issues#15]
在27面数组解构中：
`function f([first, second] = [number, number]){
    console.log(first + second);
}
f([1, 2]);
`
会报错：
`
test.ts(1,29): error TS2304: Cannot find name 'number'.
test.ts(1,37): error TS2304: Cannot find name 'number'.
`
不加上后面的`[number, number]`就不报错了。

**Comment by loskael** [comment]
确实有问题，后面的 [number, number] 应该是默认值, 正确写法如下
```typescript
function f([first, second]: [number, number] = [0, 0]) {
  console.log(first + second);
}

f([1, 2]);
```

**Comment by ghost** [comment]
恩，是同一个问题：https://github.com/angular-programming/issues/issues/6

**Comment by ghost** [comment]
多谢反馈 ~
