### ISSUE TITLE
243页，关于HTTP GET请求

### ISSUE THREAD

**Issue by kungfuboy** [angular-programming/issues#21]
在用Angular 2.4.10版本实践的时候，在书中第243页`contact.service.ts`代码段里
`import { Http } from "@angular/http";`
一句少了`Response`模块引入，报错信息为：
```
The type argument for type parameter 'T' cannot be inferred from the usage. Consider specifying the type arguments explicitly.
  Type argument candidate 'Response[]' is not a valid type argument because it is not a supertype of candidate 'Response'.
    Property 'find' is missing in type 'Response'.
```
应该改为：
`import { Http, Response } from "@angular/http";`

虽然这个错误坑了我好久，但还是谢谢你们的书，收获甚大！

**Comment by ghost** [comment]
恩，下文用到了 Response，的确需要引入这个类型。
多谢反馈 ~
