### ISSUE TITLE
在第一章遇到的疑问

### ISSUE THREAD

**Issue by kungfuboy** [angular-programming/issues#22]
随手翻到第五页的时候，章节1.5的第四自然段：

> ……过去有人提出Om在速度上比原生Javascript版本的React快了非常多……究其背后，其中一个很重要的原因是……使用了不可变数据类型……受此启发，React社区也冒出了Immutable.js，优化了Javascript这门弱类型语言对于引用对象的变化检测性能问题，也更好地提升了性能。

对这段话不太理解，请问不可变的数据类型是指强类型吗？也就像是TypeScript一样？就性能而言，Typescript比原生弱类型的Javascript更好吗？

**Comment by ghost** [comment]
1. Om是可以看做是ClosureScript上的React，Clojure 原生支持不可变数据结构（Immutable Data Structure）。
2. 那么Immutable是什么，为什么性能高？看这篇文章（https://github.com/camsong/blog/issues/3 ）就够了。
3. 遗憾的是JavaScript原生是不支持Immutable数据结构，于是借鉴ClojureScript，JavaScript世界出现了Immutable.js这个库，里头包含了常用的数据结构，如map，list，set等，基于这个库定义的这些数据是不可变的，API用法见官网：https://facebook.github.io/immutable-js/docs/
4. TypeScript 并不是一门真正运行在浏览器的语言，并不能直接运行，TypeScript的归宿是编译成JavaScript代码，所以没有性能对比这一说法。
