### ISSUE TITLE
14.4 中示例代码或有误

### ISSUE THREAD

**Issue by KevinZhang111** [angular-programming/issues#27]
14.4  P387 中 home/home.modules.ts 的示例代码中， imports: [CommonModule, SharedModule, CarouselModule], 去掉了angular-seed 中原来的 HomeRoutingModule, 但是项目此时启动依然会通过HomeRoutingModule 去启动HomeComponent，所以这里不能去掉这个 import, 否则home页面无法加载。按照书中讲解，此时项目若想成功工作，home/home.module.ts 的代码如下：

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { HomeComponent } from './home.component';
import { HomeRoutingModule } from './home-routing.module';
import { SharedModule } from '../shared/shared.module';
import { CarouselModule } from 'ng2-bootstrap/components/carousel';

@NgModule({
  imports: [CommonModule, HomeRoutingModule, SharedModule, CarouselModule],
  declarations: [HomeComponent],
  exports: [HomeComponent]
})
export class HomeModule { }

**Comment by ghost** [comment]
Hi，看得好细心，赞一个。
这个Demo里的路由经过改造的，Home模块并没有配置路由模块，而是将路由信息引入到app-routing.module里面了

**Comment by KevinZhang111** [comment]
我是按照书上的顺序在跑这个project，所以才能发现。其实我猜测的也是项目已经把angular-seed的路由部分改了，只是书上没有提到。谢谢李老师

**Comment by ghost** [comment]
恩啊，其实还是推荐把路放在各自模块里管理的。
后期我们会把这个Demo做优化
