### ISSUE TITLE
P287 组件继承示例代码疑问

### ISSUE THREAD

**Issue by KevinZhang111** [angular-programming/issues#29]
P287 有派生组件继承父组件的代码，class SortedContactAppComponent implements ContactAppComponent{} , 因为在TypeScript里，类继承用的关键字是 extends, 接口继承的关键字是 implements. 而组件本质上是一个类，所以这里让我有些迷惑。这是不是书上的一个 typo呢？

烦请老师看一下，给予澄清。多谢。

**Comment by miaotmac** [comment]
是的，是typo，我们会在下次修订中更正过来，感谢指正，谢谢！
