### ISSUE TITLE
书中样例无法运行的问题

### ISSUE THREAD

**Issue by woshixiaoqianbi** [angular-programming/issues#3]
本人初学ng2，webpack也是首次使用，一些问题还不是特别明白，clone下来书中的demo，npm start报错（应该是npm和node都是最新的问题），往作者能改善一下书中demo的代码：）

**Comment by ghost** [comment]
Hi!
是的，书中 Demo 依赖的 Node 当前是有版本要求，请确保你的 Node 版本不低于 6.0 即可。
可以使用像 nvm 类似的工具管理你的Node版本。

**Comment by woshixiaoqianbi** [comment]
恩，谢谢回复，本书对我学习ng2帮助真的很大，谢谢！：）
