### ISSUE TITLE
P239 示例代码疑似有typo

### ISSUE THREAD

**Issue by KevinZhang111** [angular-programming/issues#30]
P239 父组件示例代码中有一行 <ul *ngFor="#item in list">, 这里为何使用#？ 是否是一个typo？

**Comment by ghost** [comment]
抱歉了，在2.0.0-beta.17之前`ngFor`里可以使用`#`表示局部变量，之后就取消了这种用法了，改成let。书本这里仍然沿用了老的用法。
下个修订版会改正，多谢反馈 ~
