### ISSUE TITLE
221页el属性重定义

### ISSUE THREAD

**Issue by tinycold** [angular-programming/issues#31]
代码最开始有: private el: HTMLElement

构造函数中注入ElementRef时又将属性命名为el

**Comment by ghost** [comment]
构造函数里的el是ElementRef类型，`el.nativeElement`是HTMLElement类型，是可以赋值给类成员变量`this.el`的。
这里的问题是同一个`el`被用来表示不同的类型，的确会引起一些歧义，后面版本会改进。
