### ISSUE TITLE
通讯录源码中找不到书中的源码

### ISSUE THREAD

**Issue by lyc152** [angular-programming/issues#35]
在读本书过程中碰到了很多疑惑。如:
page103,108,109 提到的 contactItem.component.ts 在本书源码中没有找到，
另page119 中的 changeLog.component.ts 也没找到，
page121页中的 ContactCollectComponent具体实现也没找到，
还望指点迷津，谢谢！！

**Comment by ghost** [comment]
- 抱歉了，contactItem.component.ts源码文件名已经改了，改成`src/app/list/item.component.ts`，书上的例子没有一一更正过来，注意的是书上的这个文件内容是根据讲解需要渐进式更新的，没有完全跟源码同步。
- `changeLog.component.ts`是为了讲解需要，虚构出来的
- ContactCollectComponent同第一点一样，名字没有及时更新，可以参考`src/app/collection/collection.component.ts`

发版前对比过一遍代码，代码量比较大，可能有遗漏，下个版本我们会再仔细排查一遍哈 ~

**Comment by lyc152** [comment]
建议源码也是渐进式的， 不然看书会很累

**Comment by ghost** [comment]
代码渐进式指？可以再具体一点么？ ~

**Comment by loskael** [comment]
@lyc152  源码渐进式确实有必要，便于读者一步步跟进
@lizhonghui  渐进式就是说每一个章节的代码都是分开在不同目录，并且是基于前一个章节的，推荐一个这一块做得比较好的教程和源码
https://zhuanlan.zhihu.com/json-tutorial
https://github.com/miloyip/json-tutorial

**Comment by lyc152** [comment]
ng-book2 是渐进式的，他的缺点是缺乏像揭秘angular2的通讯录这样的例子

**Comment by ghost** [comment]
其实揭秘NG2书里面的例子很多代码也是从简单开始慢慢丰富的，但遗憾是暂时没有渐进过程的代码记录在github上

**Comment by lyc152** [comment]
可以理解，大家工作都比较忙的
