### ISSUE TITLE
一个问题:No provider for e!求解.

### ISSUE THREAD

**Issue by dukehq** [angular-programming/issues#38]
浏览器访问edit.component.ts组件就报以下错误:core.umd.js:2838 EXCEPTION: Uncaught (in promise): Error: Error in http://localhost:5555/app/edit/edit.component.html:3:12 caused by: No provider for e!

edit.component.html:
<div class="row edit-container">
    <div class="col-lg-3">
        <div class="sidebar">
            <tabset type="tabs">
                <tab heading="问题控件">
                    <question-select (addQuestionRequest)="onAddQuestion($event)"></question-select>
                </tab>
                <tab heading="问卷大纲">
                    <questionnaire-outline [questionnaire]="questionnaire"></questionnaire-outline>
                </tab>
            </tabset>
        </div>
    </div>
    <div class="col-lg-9 questionnaire-container">
        <questionnaire [(questionnaire)]="questionnaire" (submitQuestionnaire)="onSubmitQuestionnaire($event)"></questionnaire>
    </div>
</div>

edit.component.ts文件完全按书上代码写的.

如果注释掉一部分代码访问就没问题:
<div class="row edit-container">
    <div class="col-lg-3">
        <div class="sidebar">
            
        </div>
    </div>
    <div class="col-lg-9 questionnaire-container">
        <questionnaire [(questionnaire)]="questionnaire" (submitQuestionnaire)="onSubmitQuestionniare($event)"></questionnaire>
    </div>
</div>

**Comment by ghost** [comment]
试试在main.ts开头里加上
```
import 'core-js';
```

**Comment by ghost** [comment]
或者把更多代码信息贴出来看看？

**Comment by dukehq** [comment]
Mr Li:
    你好!
    相关代码如下:
edit.component.ts:
    import { Component,OnInit } from '@angular/core';
import {Router,ActivatedRoute} from '@angular/router';


import {QuestionType} from '../shared/model/question.model';
import {QuestionnaireModel,QuestionnaireState} from '../shared/model/questionnaire.model';
import {QuestionnaireService} from '../core/services/questionnaire.service';

@Component({
moduleId: module.id,
selector: 'sd-edit',
templateUrl: 'edit.component.html',
styleUrls: ['edit.component.css']
})
export class EditComponent implements OnInit {

private questionnaire: QuestionnaireModel;
private id: string;

constructor(private questionnaireService:QuestionnaireService, private activatedRoute:ActivatedRoute,
private router: Router) {

//初始化一个空的问卷对象
this.questionnaire = {
title: '',
starter: '',
ending: '',
state: QuestionnaireState.Created,
questionList: []
};
}

ngOnInit() {
//初始化问卷数据
this.id = this.activatedRoute.snapshot.params['id'];

if(this.id && this.id !== '0'){
//id存在，代表当前页面为编辑已有问卷页面，调用服务获取问卷对象信息
this.questionnaireService.getQuestionnaireById(this.id)
.subscribe(
questionnaire => this.questionnaire = questionnaire,
error => console.log(error)
);
}
}

onAddQuestion(type: QuestionType) {
//添加问题到问卷的问题列表
switch(type){
case QuestionType.Text:
case QuestionType.Score:
this.questionnaire.questionList.push({
title: '问题标题',
type: type,
answer: ''
});
break;
case QuestionType.SingleSelect:
this.questionnaire.questionList.push({
title: '问题标题',
type: type,
options: [{'key': 0, 'value': '选项1'}],
answer:''
});
break;
case QuestionType.MultiSelect:
this.questionnaire.questionList.push({
title: '问题标题',
type: type,
options: [{'key': 0, 'value': '选项1'}],
answer:{}
});
break;
}
}

onSubmitQuestionniare(questionnaire: QuestionnaireModel) {
//保存问卷或回收答案
if (questionnaire.state === QuestionnaireState.Created) {
if (this.id && this.id !== '0') {
//编辑已有问卷
this.questionnaireService.updateQuestionnaire(questionnaire)
.subscribe(
questionnaire => this.gotoCenter(),
error => console.log(error));
} else {
//创建新问卷
this.questionnaireService.addQuestionnaire(questionnaire)
.subscribe(
questionnaire => this.gotoCenter(),
error=> console.error(error));
}
}
}

gotoCenter() {
this.router.navigateByUrl('admin/center');
}
}


edit.component.html:
<div class="row edit-container">
<div class="col-lg-3">
<div class="sidebar">
<tabset type="tabs">
<tab heading="问题控件">
<question-select (addQuestionRequest)="onAddQuestion($event)"></question-select>
</tab>
<tab heading="问卷大纲">
<questionnaire-outline [questionnaire]="questionnaire"></questionnaire-outline>
</tab>
</tabset>
</div>
</div>
<div class="col-lg-9 questionnaire-container">
<questionnaire [(questionnaire)]="questionnaire" (submitQuestionnaire)="onSubmitQuestionniare($event)"></questionnaire>
</div>
</div>

异常如下:
    

如果我注释点HTML文件中的两个自定义控件,则不会报上述错误:
    <div class="row edit-container">
<div class="col-lg-3">

</div>
<div class="col-lg-9 questionnaire-container">
<questionnaire [(questionnaire)]="questionnaire" (submitQuestionnaire)="onSubmitQuestionniare($event)"></questionnaire>
</div>
</div>



Best regards
DukeHQ
Job:Software En
Mobile : 1812383****
E-mail : fegxiao@yeah.net
Addr :China
 
发件人： 李仲辉
发送时间： 2017-06-05 19:52
收件人： angular-programming/issues
抄送： dukehq; Author
主题： Re: [angular-programming/issues] 一个问题:No provider for e!求解. (#38)
或者把更多代码信息贴出来看看？

**Comment by dukehq** [comment]
上一封邮件中的异常是截图的,你可能看不到.
这里补发异常的文本形式:
app.component.ts:15 Environment config Object {API: "https://demo.com", ENV: "DEV"}
core.umd.js:79 Angular 2 is running in the development mode. Call enableProdMode() to enable the production mode.
core.umd.js:2838 EXCEPTION: Uncaught (in promise): Error: Error in http://localhost:5555/app/edit/edit.component.html:3:12 caused by: No provider for e!
ErrorHandler.handleError @ core.umd.js:2838
next @ core.umd.js:6424
schedulerFn @ core.umd.js:5722
SafeSubscriber.__tryOrUnsub @ Subscriber.ts:238
SafeSubscriber.next @ Subscriber.ts:190
Subscriber._next @ Subscriber.ts:135
Subscriber.next @ Subscriber.ts:95
Subject.next @ Subject.ts:61
EventEmitter.emit @ core.umd.js:5714
NgZone.triggerError @ core.umd.js:6018
onHandleError @ core.umd.js:5997
ZoneDelegate.handleError @ zone.js?1496712385577:207
Zone.runGuarded @ zone.js?1496712385577:113
_loop_1 @ zone.js?1496712385577:379
drainMicroTaskQueue @ zone.js?1496712385577:386
ZoneTask.invoke @ zone.js?1496712385577:308
core.umd.js:2843 ORIGINAL STACKTRACE:
ErrorHandler.handleError @ core.umd.js:2843
next @ core.umd.js:6424
schedulerFn @ core.umd.js:5722
SafeSubscriber.__tryOrUnsub @ Subscriber.ts:238
SafeSubscriber.next @ Subscriber.ts:190
Subscriber._next @ Subscriber.ts:135
Subscriber.next @ Subscriber.ts:95
Subject.next @ Subject.ts:61
EventEmitter.emit @ core.umd.js:5714
NgZone.triggerError @ core.umd.js:6018
onHandleError @ core.umd.js:5997
ZoneDelegate.handleError @ zone.js?1496712385577:207
Zone.runGuarded @ zone.js?1496712385577:113
_loop_1 @ zone.js?1496712385577:379
drainMicroTaskQueue @ zone.js?1496712385577:386
ZoneTask.invoke @ zone.js?1496712385577:308
core.umd.js:2844 Error: Uncaught (in promise): Error: Error in http://localhost:5555/app/edit/edit.component.html:3:12 caused by: No provider for e!
    at resolvePromise (zone.js?1496712385577:429)
    at resolvePromise (zone.js?1496712385577:414)
    at zone.js?1496712385577:462
    at ZoneDelegate.invokeTask (zone.js?1496712385577:236)
    at Object.onInvokeTask (core.umd.js:5967)
    at ZoneDelegate.invokeTask (zone.js?1496712385577:235)
    at Zone.runTask (zone.js?1496712385577:136)
    at drainMicroTaskQueue (zone.js?1496712385577:368)
    at XMLHttpRequest.ZoneTask.invoke (zone.js?1496712385577:308)



Best regards
DukeHQ
Job:Software En
Mobile : 1812383****
E-mail : fegxiao@yeah.net
Addr :China
 
发件人： fegxiao@yeah.net
发送时间： 2017-06-06 09:22
收件人： angular-programming/issues
主题： Re: Re: [angular-programming/issues] 一个问题:No provider for e!求解. (#38)
Mr Li:
    你好!
    相关代码如下:
edit.component.ts:
    import { Component,OnInit } from '@angular/core';
import {Router,ActivatedRoute} from '@angular/router';


import {QuestionType} from '../shared/model/question.model';
import {QuestionnaireModel,QuestionnaireState} from '../shared/model/questionnaire.model';
import {QuestionnaireService} from '../core/services/questionnaire.service';

@Component({
moduleId: module.id,
selector: 'sd-edit',
templateUrl: 'edit.component.html',
styleUrls: ['edit.component.css']
})
export class EditComponent implements OnInit {

private questionnaire: QuestionnaireModel;
private id: string;

constructor(private questionnaireService:QuestionnaireService, private activatedRoute:ActivatedRoute,
private router: Router) {

//初始化一个空的问卷对象
this.questionnaire = {
title: '',
starter: '',
ending: '',
state: QuestionnaireState.Created,
questionList: []
};
}

ngOnInit() {
//初始化问卷数据
this.id = this.activatedRoute.snapshot.params['id'];

if(this.id && this.id !== '0'){
//id存在，代表当前页面为编辑已有问卷页面，调用服务获取问卷对象信息
this.questionnaireService.getQuestionnaireById(this.id)
.subscribe(
questionnaire => this.questionnaire = questionnaire,
error => console.log(error)
);
}
}

onAddQuestion(type: QuestionType) {
//添加问题到问卷的问题列表
switch(type){
case QuestionType.Text:
case QuestionType.Score:
this.questionnaire.questionList.push({
title: '问题标题',
type: type,
answer: ''
});
break;
case QuestionType.SingleSelect:
this.questionnaire.questionList.push({
title: '问题标题',
type: type,
options: [{'key': 0, 'value': '选项1'}],
answer:''
});
break;
case QuestionType.MultiSelect:
this.questionnaire.questionList.push({
title: '问题标题',
type: type,
options: [{'key': 0, 'value': '选项1'}],
answer:{}
});
break;
}
}

onSubmitQuestionniare(questionnaire: QuestionnaireModel) {
//保存问卷或回收答案
if (questionnaire.state === QuestionnaireState.Created) {
if (this.id && this.id !== '0') {
//编辑已有问卷
this.questionnaireService.updateQuestionnaire(questionnaire)
.subscribe(
questionnaire => this.gotoCenter(),
error => console.log(error));
} else {
//创建新问卷
this.questionnaireService.addQuestionnaire(questionnaire)
.subscribe(
questionnaire => this.gotoCenter(),
error=> console.error(error));
}
}
}

gotoCenter() {
this.router.navigateByUrl('admin/center');
}
}


edit.component.html:
<div class="row edit-container">
<div class="col-lg-3">
<div class="sidebar">
<tabset type="tabs">
<tab heading="问题控件">
<question-select (addQuestionRequest)="onAddQuestion($event)"></question-select>
</tab>
<tab heading="问卷大纲">
<questionnaire-outline [questionnaire]="questionnaire"></questionnaire-outline>
</tab>
</tabset>
</div>
</div>
<div class="col-lg-9 questionnaire-container">
<questionnaire [(questionnaire)]="questionnaire" (submitQuestionnaire)="onSubmitQuestionniare($event)"></questionnaire>
</div>
</div>

异常如下:
    

如果我注释点HTML文件中的两个自定义控件,则不会报上述错误:
    <div class="row edit-container">
<div class="col-lg-3">

</div>
<div class="col-lg-9 questionnaire-container">
<questionnaire [(questionnaire)]="questionnaire" (submitQuestionnaire)="onSubmitQuestionniare($event)"></questionnaire>
</div>
</div>



Best regards
DukeHQ
Job:Software En
Mobile : 1812383****
E-mail : fegxiao@yeah.net
Addr :China
 
发件人： 李仲辉
发送时间： 2017-06-05 19:52
收件人： angular-programming/issues
抄送： dukehq; Author
主题： Re: [angular-programming/issues] 一个问题:No provider for e!求解. (#38)
或者把更多代码信息贴出来看看？

**Comment by ghost** [comment]
edit.component.html 里用了 tabset，这是第三方库的组件，记得要把包含这个组件的模块import进来。
看看这里的#11行
https://github.com/angular-programming/angular2-questionnaire/blob/master/frontend/src/client/app/edit/edit.module.ts#L11

**Comment by dukehq** [comment]
在模块文件edit.module.ts中,我做了以下引入:

import {TabsModule} from 'ngx-bootstrap';

edit.module.ts完整内容如下:

import { NgModule } from '@angular/core';

import { CommonModule } from '@angular/common';
import {EditSharedModule} from './shared/edit-shared.module';
import {EditComponent} from './edit.component';
import {QuestionnaireModule} from '../shared/questionnaire/questionnaire.module';
import {TabsModule} from 'ngx-bootstrap';
import {EditRoutingModule} from './edit-routing.module';


@NgModule({
imports: [
CommonModule,
EditSharedModule,
QuestionnaireModule,
TabsModule,
EditRoutingModule
],
exports: [EditComponent,EditSharedModule],
declarations: [EditComponent],
})
export class EditModule { }



Best regards
DukeHQ
Job:Software En
Mobile : 1812383****
E-mail : fegxiao@yeah.net
Addr :China
 
发件人： 李仲辉
发送时间： 2017-06-06 09:34
收件人： angular-programming/issues
抄送： dukehq; Author
主题： Re: [angular-programming/issues] 一个问题:No provider for e!求解. (#38)
edit.component.html 里用了 tabset，这是第三方库的组件，记得要把包含这个组件的模块import进来。
看看这里的#11行

**Comment by dukehq** [comment]
我好像找到了问题的所在了,
模块TabsModule导入时,要用
TabsModule.forRoot(),而不是直接用TabsModule.........o(╯□╰)o
刚才看了下ngx-bootstrap api doc
例子如下:
// RECOMMENDED (doesn't work with system.js)
import { TabsModule } from 'ngx-bootstrap/tabs';
// or
import { TabsModule } from 'ngx-bootstrap';
@NgModule({
  imports: [TabsModule.forRoot(),...]
})
export class AppModule(){}
顺便请教一下:它这里这个static func forRoot()是什么意思?我看很多地方有这种用法.



Best regards
DukeHQ
Job:Software En
Mobile : 1812383****
E-mail : fegxiao@yeah.net
Addr :China
 
发件人： fegxiao@yeah.net
发送时间： 2017-06-06 09:44
收件人： angular-programming/issues
主题： Re: Re: [angular-programming/issues] 一个问题:No provider for e!求解. (#38)
在模块文件edit.module.ts中,我做了以下引入:

import {TabsModule} from 'ngx-bootstrap';

edit.module.ts完整内容如下:

import { NgModule } from '@angular/core';

import { CommonModule } from '@angular/common';
import {EditSharedModule} from './shared/edit-shared.module';
import {EditComponent} from './edit.component';
import {QuestionnaireModule} from '../shared/questionnaire/questionnaire.module';
import {TabsModule} from 'ngx-bootstrap';
import {EditRoutingModule} from './edit-routing.module';


@NgModule({
imports: [
CommonModule,
EditSharedModule,
QuestionnaireModule,
TabsModule,
EditRoutingModule
],
exports: [EditComponent,EditSharedModule],
declarations: [EditComponent],
})
export class EditModule { }



Best regards
DukeHQ
Job:Software En
Mobile : 1812383****
E-mail : fegxiao@yeah.net
Addr :China
 
发件人： 李仲辉
发送时间： 2017-06-06 09:34
收件人： angular-programming/issues
抄送： dukehq; Author
主题： Re: [angular-programming/issues] 一个问题:No provider for e!求解. (#38)
edit.component.html 里用了 tabset，这是第三方库的组件，记得要把包含这个组件的模块import进来。
看看这里的#11行

**Comment by ghost** [comment]
恩，不排除文档已经有更新，当前github上的代码还是用这比较老的ng-bootstrap版本。按照文档说的，在根模块import这个：TabsModule.forRoot()

forRoot() 在根模块使用，可以用来动态配置模块注入的服务，而不仅限于模块内固定注入好的服务。还有一个作用就是这里解释比较清楚：https://stackoverflow.com/questions/39653072/how-to-use-forroot-within-feature-modules-hierarchy

**Comment by dukehq** [comment]
非常感谢你关注我的问题.
谢谢.



Best regards
DukeHQ
Job:Software En
Mobile : 1812383****
E-mail : fegxiao@yeah.net
Addr :China
 
发件人： 李仲辉
发送时间： 2017-06-06 10:32
收件人： angular-programming/issues
抄送： dukehq; Author
主题： Re: [angular-programming/issues] 一个问题:No provider for e!求解. (#38)
恩，不排除文档已经有更新，当前github上的代码还是用这比较老的ng-bootstrap版本。按照文档说的，在根模块import这个：TabsModule.forRoot()
forRoot() 在根模块使用，可以用来动态配置模块注入的服务，而不仅限于模块内固定注入好的服务。
