### ISSUE TITLE
书中的变化检测没怎么看懂

### ISSUE THREAD

**Issue by sunnut** [angular-programming/issues#39]
如果pure js实现双向数据绑定，如何检测一个变量变化了，更新dom组件

**Comment by ghost** [comment]
检测变量变化的这些逻辑是通过@angular/compiler生成的，检测到数据更新之后，会调用DOM API精准更新DOM节点（DOM节点的信息也是通过编译器辅助生成），跟v-dom这种方式有差别。
关于变化检测这篇文章写得不错：https://hackernoon.com/everything-you-need-to-know-about-change-detection-in-angular-8006c51d206f
