### ISSUE TITLE
国际化

### ISSUE THREAD

**Issue by sunnut** [angular-programming/issues#4]
ng2-translate国际化的词条(assets/i18n/en.json、zh.json)，用webpack方式的话，编译后怎么拷贝过去，目前编译后dist目录找不到

**Comment by ghost** [comment]
ng2-tranlate官方有解决方案的，使用`copy-webpack-plugin`即可 ~ 
查看这个issue了解更多：https://github.com/ngx-translate/core/issues/325

**Comment by sunnut** [comment]
谢了哈 解决了 之前不熟 找半天也没解决
