### ISSUE TITLE
你们系统换肤问题有经验么

### ISSUE THREAD

**Issue by sunnut** [angular-programming/issues#41]
Angular2项目切换时，根据选择的皮肤，组件加载相应的css，可以做到么

**Comment by ghost** [comment]
1. 可以将各种皮肤预先设置在组件内部，通过:host-context(https://angular.io/guide/component-styles#host-context )来切换。
2. 如果要做到动态加载css的话，想了下，可以不用Angular体系内加载css，利用全局样式来控制皮肤，即自己写代码手动加载，更新css，然后重新渲染Angular

**Comment by sunnut** [comment]
1、其实不太了解为啥用:host-context(.theme-xxx) .myModule {XXXX}，直接.theme-xxx .myModule {XXXX}不就行了么，如果祖先元素没有这个class，也不会生效啊。
2、我们用webpack，引用公用css用的都是手动import 'xxxx.css';   不了解怎么动态加载css啊。

**Comment by ghost** [comment]
1. 恩，可以（host-context是用在shadow-dom之下）
2. 使用webpack2的import()功能或者require.ensure()实现动态加载，加载后写入DOM的逻辑需要你手动编写
