### ISSUE TITLE
181页有小错误

### ISSUE THREAD

**Issue by Luin-Li** [angular-programming/issues#46]
181页NgForm表单局部变量部分
原文：
```
{
neme：‘李四’，
telNum:'123456789'
}
```
这个JSON对象的属性名neme，根据上下文，应为contactName。

**Comment by ghost** [comment]
恩，https://github.com/angular-programming/issues/issues/17

**Comment by annilq** [comment]
下面的NgModel控件局部变量部分
将[{ngModel }]初始化为联系人姓名部分，应该将[{ngModel }]改成[(ngModel)]

**Comment by ghost** [comment]
恩，是的。见：https://github.com/angular-programming/issues/issues/18
