### ISSUE TITLE
书中的若干疑问

### ISSUE THREAD

**Issue by sunnut** [angular-programming/issues#47]
一、异步事件被zones捕获，哪个自定义事件决定去执行变化检测
有的写onUnstable、有的写onMicrotaskEmpty。
以下三个自定义事件，我这样理解可以么
1、onUnstable，异步事件启动，执行异步之前。
2、onMicrotaskEmpty，异步事件完成了，回调函数开始。
3、onStable，回调函数完成。
如果这么理解了，按道理应该onStable去通知执行变化检测啊，因为数据没变化，通知也没用啊。
另外，Angular双向数据绑定原理，书中好像没有涉及，检测数据变化后，怎么通知视图的啊，视图变化，怎么更新到变量啊。
二、依赖注入底层怎么实现的啊，Angular的实现方式和Spring一样么，反射、工厂模式啥的。

**Comment by ghost** [comment]
很不错的问题！可以深入探讨一下
首先需要理解的是，异步事件可以看成一个一个的Task。
- 那么当有异步事件触发时，产生新的Task待执行，NgZone认为该Zone变得不稳定了，所以在执行这个异步任务之前先触发 onUnstable 事件，可以在Task执行前做一些额外操作。
- 接下来，开始执行这个Task，这里涉及到VM turn执行知识。Task 分为 Macrotask 和 Microtask，一次 VM Turn 会执行一个 Macrotask 和当前所有的 Microtask，然后再触发下一次 VM Turn，所以监听 MicrotaskEmpty 事件大概就可以知道一次VM Turn执行完的时机，这时候触发一次变化检测来更新视图是比较合适的。
- 当变化检测执行完，这时候便触发 onStable 事件。

所以他们的执行顺序大概是：
```
onUnstable
onMicrotaskEmpty --> 触发变化检测
onStable
```

每次变化检测对于Angular来说并不知道数据是否发生变化，所以默认情况下，每次变化检测都需要遍历组件数据模型，有变化才更新视图。组件的数据模型比对是经过Angular编译器优化，速度很快，不过呢，即使这样，这里的优化空间还是很大，所以就有 ChangeDetectionStrategy 和
 ChangeDetectionRef 等API。

**Comment by ghost** [comment]
Angular没有原生双向数据绑定执行，都是通过属性绑定和事件绑定联合，来模拟双向绑定的

**Comment by sunnut** [comment]
多谢~
1、一系列VM turn去执行Task，每次都触发变化检测，每次检测完都要执行OnStable，这么解释就是回调函数一定是在某个VM turn执行之前完成的，VM turn不光负责task完成，而且要保证task回调函数执行完，它才会终止。毕竟数据变化是在回调函数中。
2、Angular双向绑定具体怎么模拟啊，原理是啥，研究过么。。

**Comment by ghost** [comment]
1. 第一点关于VM Turn 说法不太准确，VM Turn 为一次事件循环，每次循环开始会从 Macrotask 队列里取出一个 Task（点击事件回调函数，或 setTimeout 回调函数等）来执行，这些回调函数可能会产生更多的 Macrotask 或者是 Microtask，新的 Macrotask 存在队列里，在后面的 VM Turn 里依次执行，而 所有的
 Microtask 会在当前的 Macrotask 执行完马上执行，即在同一个 VM Turn 中执行，所有的 Microtask 都执行完后，会触发 MicrotaskEmpty 事件，即触发变化检测。
> 关于 Macrotask  和 Microtask 现在中文资料也比较多了，如 https://github.com/ccforward/cc/issues/48 
2. 双向绑定无非就是 NgModel 指令，这个指令就是用来把属性绑定和事件绑定联合起来的，完整的例子是：
```
<input [ngModel]="itemValue" (ngModelChange)="itemValue=$event" />
```
像 `[()]` 是是一种语法糖，下面的代码会被转化成上面的代码：
```
<input [(ngModel)]="itemValue" />
```
> 关于这块内容，官网也有描述：https://angular.io/guide/template-syntax#two-way-binding---

**Comment by sunnut** [comment]
好的，有劳，有空仔细看看官网~
