### ISSUE TITLE
webpack的代理

### ISSUE THREAD

**Issue by sunnut** [angular-programming/issues#5]
项目webpack编译打包后，放入服务器，想要代理生效怎么弄哈，下述代码貌似没生效，调用的接口是本地地址，是不是下述配置只对开发模式生效。
proxy: {
            '/api/*': {
                target: 'http://localhost:8888',
                secure: false
            }
        }

**Comment by ghost** [comment]
这种代理配置原本就是方便你本地开发访问接口时避免跨域问题，生产环境需要代理通常使用Web Server配置，如nginx。

**Comment by sunnut** [comment]
生产环境下，前段打包后放入一个nginx，微服务譬如另外个端口，怎么调用该接口啊，不用代理

**Comment by sunnut** [comment]
是的，nginx配个代理就行
