### ISSUE TITLE
装饰器组合部分例子输出是错误的

### ISSUE THREAD

**Issue by jusfeel** [angular-programming/issues#50]
3.8.6装饰器组合部分，装饰器的调用顺序的描述虽然没有写错，但最重要的，关于结果返回函数的调用顺序没有说明，因为它正好相反。
神奇的是，给出的例子代码没有问题，但是输出竟然是错的。出错的原因真是耐人寻味。

**Comment by miaotmac** [comment]
我们已经修复过来，执行顺序手抖搞错了，下个版本会修复。非常感谢提出指正，谢谢!
