### ISSUE TITLE
导入模块问题

### ISSUE THREAD

**Issue by sunnut** [angular-programming/issues#54]
A模块导入B模块，本来只想用B模块的exports组件，结果B模块的路由把A模块路由覆盖了，有好的解决方法么

**Comment by willywang** [comment]
首先，Angular中路由的配置会合并
其次，路由的匹配跟路由配置import的顺序相关（非覆盖）

在你的case中，A模块自身`import`了路由配置`RoutesA[]`（实际上为一个数组），导入的B模块假如也有路由配置`RoutesB[] `。

假设在A模块中`RoutesA`的导入顺序在`RoutesB`之前，那么路由匹配的顺序是先依次匹配`RoutesA`中的每一项，如有符合规则的匹配则认为匹配成功，否则继续匹配`RoutesB`的每一项，直到找到一个符合规则的配置项。
因此，在你的case中，如果B模块的路由配置 **_“覆盖”_** 了A模块，那很可能是因为B模块的导入顺序在RoutesA之前。

通常为了避免这种问题，可以把路由配置和可共享的组件都单独为一个module，如：
`b-routing.module`
`b-share.module`

在`b.module`中导入`b-routing.module`和`b-share.module`
而在`a.module`中只要按需导入`b-share.module`即可

**Comment by sunnut** [comment]
确实是个解决方法，只要新建share模块就行了，路由没必要新建模块了
