### ISSUE TITLE
关于模块的疑问？

### ISSUE THREAD

**Issue by qqaimh** [angular-programming/issues#57]
### 任何包含顶级import或者export的文件都被当成一个模块。
我再网上找了好久也没搞清楚关于“顶级import或者export”，能不能说一下什么是“顶级export”，谢谢谢

**Comment by ghost** [comment]
某JS文件
```js
// 顶级
import xxx from 'xxx'

// 非顶级
{
  import xxx from 'xxx'
}
```
import放在非顶级会报错，实际去掉『顶级』二字没有歧义

**Comment by qqaimh** [comment]
那expor也是这样的吗？

**Comment by ghost** [comment]
是的。
es6的import跟AMD, commonjs这些模块工具不同，一个是语法层面，一个模拟的，想AMD的require是可以放在块作用域内`{}`的的
