### ISSUE TITLE
同步请求&国际化词条分模块写

### ISSUE THREAD

**Issue by sunnut** [angular-programming/issues#7]
1、Angular的http请求怎么设置同步哈。
2、ng2-translate的国际化，怎么分文件编写，本来gulp我们是写脚本把文件合并到en.json、zh.json，如果webpack应该怎么弄哈。

**Comment by loskael** [comment]
问题1: 一般不建议设置同步, 参考 https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/Synchronous_and_Asynchronous_Requests
问题2: 可以参考 https://github.com/ngx-translate/core/tree/master/examples/webpack

**Comment by ghost** [comment]
哈哈，楼上正解 ~

**Comment by sunnut** [comment]
问题2没解决哈，各个模块的开发人员可以有自己的词条模块么。统一去编辑en.json不太好吧。
另外，angular http没有同步请求么，存在类似complete的方法么，不管成功与否都会执行

**Comment by ghost** [comment]
angular http 模块是基于 [RxJS](http://reactivex.io/rxjs/) 实现的，类似的 complete 方法是这样实现的：
```
http.get(url)
  .finally(() => { 
    // do something 
  })
  .subscribe()
```
使用 finally 这个operator 之前记得先 import
```
import 'rxjs/add/operator/finally';
```

**Comment by sunnut** [comment]
哦哦 谢啦
