### ISSUE TITLE
第327页模块延迟加载的列子运行时报错，请帮忙指导下。谢谢

### ISSUE THREAD

**Issue by dajian166** [angular-programming/issues#9]
1.在通讯录列子中新增了一个模块文件p238.module.ts，用于懒加载。
const operateRoutes: Routes = [
    { path: "p238",component: ParentComponent}
];
@NgModule({
    imports: [CommonModule, FormsModule, RouterModule.forChild(operateRoutes)],
    declarations: [ParentComponent, ChildComponent]
})
export class P238Module {}

2.在app.routes.ts根路由配置中，添加如下内容。
   {
        path: "p238",
        loadChildren:'app/p238/p238.module#P238Module'
    }
3.运行时报错，如果不使用模块懒加载是正常的，感觉跟webpack有关。请帮忙指导下。
![image](https://cloud.githubusercontent.com/assets/26181048/23577304/99c74f9c-00f6-11e7-9ff7-2b6a7762dc4c.png)

**Comment by ghost** [comment]
谢谢反馈~
如果应用程序是基于`SystemJS`来实现模块加载的话，按照书本上的配置可以实现的。
但书本上的示例代码是基于 webpack 来构建，所以仅仅是改成 `loadChildren` 是不够的，例如还需要把懒加载的部分通过 webpack 打一个独立的包，并且指定加载工具等。

虽然`loadChildren`后面也可以接一个 function 手动加载，如：
```
loadChildren: () => System.import('somePath'),
```
但这样与本例的 webpack 方案不兼容。

这里的编写确实是我们的疏忽！

如果需要实现 webpack 下的的懒加载，需要结合 webpack 本身提供的按需加载特性，可参考我翻译的这篇文章：https://github.com/lizhonghui/blog/issues/13
